# @package _group_
_target_: carol.models.DeterministicMLP
device: ${device}
num_layers: 4
in_size: ???
out_size: ???
ensemble_size: 1
hid_size: 200
deterministic: true
activation_fn_cfg:
  _target_: carol.modules.vrlnn.ReLU # torch.nn.SiLU 
