# @package _group_
_target_: carol.models.GaussianMLP
device: ${device}
num_layers: 4
in_size: ???
out_size: ???
ensemble_size: 1
hid_size: 200
deterministic: false
activation_fn_cfg:
  _target_: carol.modules.vrlnn.ReLU # torch.nn.ReLU # torch.nn.ReLU
